image: rust:1.76-bookworm
pipelines:
  default:
    - step:
        script:
          - rustup component add rustfmt
          - cargo fmt --all --check
          - cd apps/octranspo/OCTranspo-Carleton/
          - cargo fmt --all --check
        #   - apt-get update -y && apt-get install -y libgstreamer-plugins-base1.0-dev libseat-dev libinput-dev libxkbcommon-dev
        #   - cargo build --all --release
        # artifacts:
        #   - target/release/benchmark_cmd
        #   - target/release/libswall.so
        #   - target/release/rt-encoding
        #   - target/release/swall_compositor
        #   - target/release/wlr_capture
